spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    locale: zh_CN

  sleuth:
    sampler:
      probability: 1
  zipkin:
    baseUrl: http://cluster-test-zipkin-server:9411
    
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  type-handlers-package: com.mic.pro.common.mybatis
    
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试，false表示只有GET请求会重试
  
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  metrics:
    tags:
      application: ${spring.application.name}
      instance: ${eureka.instance.instance-id}  
