spring:
  datasource:
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wbs?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: MYSQL-HIKARI
      connection-test-query: SELECT 1
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 20000
      connection-timeout: 3000
